trigger:
- master

variables:
  sdkVersion: '5.0.100-preview.5.20279.10'
  project: 'NuGetCacheClearer/NuGetCacheClearer.csproj'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK 3.1'
    inputs:
      packageType: sdk
      version: '$(sdkVersion)'

  - task: DotNetCoreCLI@2
    displayName: 'Restore project'
    inputs:
      projects: '$(project)'
      command: restore
      feedsToUse: config
      nugetConfigPath: NuGet.Config

  - script: dotnet publish $(project) -c Release -f net48 -o build\net48
    displayName: 'Publish project as net48'

  - script: del build\net48\*.pdb
    displayName: 'Remove PDBs'

  - task: ArchiveFiles@2
    displayName: 'Archive'
    inputs:
      rootFolderOrFile: 'build\net48'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)\NuGetCacheClearer.Fx.zip'

  - script: dotnet publish $(project) -c Release -f netcoreapp3.1 -o build\netcoreapp3.1 --self-contained false
    displayName: 'Publish project as netcoreapp3.1 FDE'

  - script: del build\netcoreapp3.1\*.pdb
    displayName: 'Remove PDBs'

  - script: del build\netcoreapp3.1\*.json
    displayName: 'Remove JSONs'

  - task: ArchiveFiles@2
    displayName: 'Archive'
    inputs:
      rootFolderOrFile: 'build\netcoreapp3.1'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)\NuGetCacheClearer.CoreFx.zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      artifactName: 'publish'
